version: '3'

services:
  simple-web:
    image: jb1r/netflex-simple-web
    ports:
      - 80:80
    container_name: simple-web

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
